FROM python:stretch

# ARG PASS
# ENV PASS=${PASS}
RUN ls -la
COPY . /app
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt


ENTRYPOINT ["gunicorn", "-b", ":8080", "app:app"]
# ENTRYPOINT ["flask","run"]